Insercao dos elementos de frontend
joao-evaristo/Rails_Docker pull request #6
Opened 2022-12-01 01:42 UTC by gaschrader

Insercao dos arquivos referentes ao frontend no projeto principal

2022-12-01 15:52 UTC, joao-evaristo requested changes

2022-12-01 15:52 UTC, joao-evaristo commented on app/controllers/usuarios_controller.rb
> -      params.require(:usuario).permit(:nome, :data_nascimento, :telefone, :email, :password, :password_confirmation)
Não pode alterar essa linha. Precisa manter como data_nascimento.

2022-12-01 15:52 UTC, joao-evaristo commented on app/views/usuarios/login.html.erb
> -<%= vite_javascript_tag 'login' %>
As tags do vite são necessárias para o funcionamento do Vue js na página.

2022-12-01 15:52 UTC, joao-evaristo commented on app/views/welcome/login.html.erb
> +<%= stylesheet_link_tag "login" %=>
Aqui a tag tá fechada de maneira incorreta.

2022-12-02 17:29 UTC, gaschrader commented on app/views/usuarios/login.html.erb
> -<%= vite_javascript_tag 'login' %>
Arrumado.

2022-12-02 17:29 UTC, gaschrader commented on app/views/welcome/login.html.erb
> +<%= stylesheet_link_tag "login" %=>
Arrumado.

2022-12-02 22:03 UTC, joao-evaristo approved these changes

2022-12-02 22:03 UTC, merged