Frontend implementation
joao-evaristo/Rails_Docker pull request #8
Opened 2022-12-07 16:19 UTC by gaschrader

Inserção de novas páginas do front end, todas com suas funcionalidades anteriores funcionais. Aleḿ disso, alguns elementos de responsividade geral do site foram incluídos.

2022-12-07 16:34 UTC, joao-evaristo requested changes

2022-12-07 16:34 UTC, joao-evaristo commented on app/views/usuarios/_form.html.erb
> +                        <%= form.text_field :data_nascimento, class: "edit-field" %>
Mudar o tipo do form para date_field

2022-12-07 16:34 UTC, gaschrader commented on app/views/usuarios/_form.html.erb
> +                        <%= form.text_field :data_nascimento, class: "edit-field" %>
arrumei

2022-12-10 23:03 UTC, joao-evaristo approved these changes

2022-12-10 23:04 UTC, merged